<Project Sdk="Microsoft.NET.Sdk.Worker">

	<PropertyGroup>
		<TargetFramework>net7.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>dotnet-Publisher-21ea0fa7-4dff-4e72-ab2f-17cef8e49743</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MassTransit" Version="8.2.5" />
		<PackageReference Include="MassTransit.RabbitMQ" Version="8.2.5" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="7.0.0" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="7.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Shared\Shared.csproj" />
	</ItemGroup>

</Project>