<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Order.OutBox.Table.Publisher.Service-9499fa34-1d9c-45ce-a56d-3de00fc26e3a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.35" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.2.5" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.1.5" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="7.0.0" />
    <PackageReference Include="Quartz" Version="3.13.0" />
    <PackageReference Include="Quartz.Extensions.DependencyInjection" Version="3.13.0" />
    <PackageReference Include="Quartz.Extensions.Hosting" Version="3.13.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\SagaPatternOrchestrationPractice\Shared\Shared.csproj" />
  </ItemGroup>
</Project>
